### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by pamoonpa** [newbuxcoin/buxcoin#1]
Buxcoin is not based on Blockchain nor even smartcontract. Actually buxcoin is MLM based ponzi scheme. BuxCoin is a Scam, CashFinex Exchange as well a Scam !!! It's a clear scam same like BitConnect, OneCoin, Gira Coin, GandhiJi Coin, Mcap, DavorCoin, RegalCoin, etc.. Now a days all scammers are in Crypto, Be aware people don't get scammed

**Comment by faizanahmed313** [comment]
can i ask you what is scam in this project .because it has running blockchain explorell and has 3rd generation of blockchain .and running exchange cashfinex

**Comment by pamoonpa** [comment]
1 month before a massage run at app.bitsolives.com now still running what
is this. What is your team doing.

**Comment by pamoonpa** [comment]
1 month before a massage run at app.bitsolives.com now still running
cashfinex update missing coin. What is your team doing.

**Comment by ashgun16** [comment]
But they are not taking btc like bitconnect did plus new revenue generated
is distributed among networkers as such company has no profit

**Comment by pamoonpa** [comment]
This is mlm base coin like one coin bitconect etc not block chain based..

**Comment by mmozey** [comment]
It clearly shows mr. pamoonpa you are just on your smeer compaign but you completely have no idea of what Buxcoin stands for. Buxcoin uses temporally mlm as an approach to distribute its 350m coins because it didn't use ICO method. Check out its block chain explorer and many other key information on www.buxcoins.com and be educated and probably if you are honest enough you apologize for your earlier negative comments
